### ISSUE TITLE
TimeoutError: waiting for selector ".app" failed

### ISSUE THREAD

**Issue by Nightmare204** [vasani-arpit/WBOT#144]
I'm trying to use the compiled program version 0.12.6 for windows, but it fails after launching chrome when the app is trying to configure the smart reply...

**To Reproduce**
1. Just launched the app, and logged in whatsapp web.

**Screenshots**
![error](https://user-images.githubusercontent.com/4441252/83822252-20928580-a696-11ea-9246-73ca99b6eb91.png)

**App information (please complete the following information):**
 - Version 0.12.6
 - OS: Windows 10

**Comment by ruesagashi** [comment]
that error same happend to me, but i have backup yesterday when browser whatsapp still not update. i was try when use whatsapp today still TimeoutError near smartreplay

**Comment by mfogaca** [comment]
I have the same issue here.

**Comment by ojoaoteixeira** [comment]
I have the same issue here.

**Comment by ibnclaudius** [comment]
Same here.

**Comment by vasani-arpit** [comment]
Thanks for generating issue and looking into errors !!

The issue was due to a smart reply feature which wbot is trying to add into the whatsapp UI. I have put that feature aside for now to get the rest of the things working.

Please pull/download the latest version and the issue should be resolved.
