### ISSUE TITLE
I want to send message to a number which I have not saved in my contacts

### ISSUE THREAD

**Issue by ParshwaS** [vasani-arpit/WBOT#148]
I want to send message to a number which I have not saved in my contacts. Is it currently possible?

**Comment by vasani-arpit** [comment]
It is possible but I don't recommend it. WA will detect it right away and will ban your number.

**Comment by chalfling** [comment]
Is there a way to add a contact number and then send him a message?

**Comment by vasani-arpit** [comment]
@chalfling yes there is but I don't recommend it either because WhatsApp can detect it and ban your phone after several messages. Have a look at here.
 https://scontent.whatsapp.net/v/t61.22868-34/69510151_652112781951150_6923638360331596993_n.pdf/Stopping-Abuse-white-paper.pdf?_nc_sid=2fbf2a&_nc_ohc=jweCI-fn0kcAX-unjd0&_nc_ht=scontent.whatsapp.net&oh=ff4b2d73c314f9f1c2dcad939f26b7e6&oe=5F8BCA0F

**Comment by chalfling** [comment]
@vasani-arpit Thank you very much!
