### ISSUE TITLE
Nacl Helper Process

### ISSUE THREAD

**Issue by indragunawan82** [vasani-arpit/WBOT#223]
After installation in linux, i got error :

![image](https://user-images.githubusercontent.com/9045625/115944463-19f44300-a4e0-11eb-944e-24839fde0bb3.png)

**Comment by vasani-arpit** [comment]
This is a problem from puppeteer(chromium) side. 

Please add `'--disable-setuid-sandbox'` in the list of arguments array in `constats.js` and try.

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/115958609-5486cb80-a532-11eb-8ecb-02cd54ecbfc5.png)
 

still same

**Comment by vasani-arpit** [comment]
I am assuming you are built the project again or running it wia `npm run start`

another thing which you can cross check is puppeteer requires following packages installed in order to run properly. Make sure you have them all.

sudo apt update && sudo apt install -y gconf-service libgbm libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

the above is for ubuntu.

**Comment by indragunawan82** [comment]
still same ,  
have u tried this in ubuntu 20?

**Comment by vasani-arpit** [comment]
Yes. Do one thing. Try to run hello world of puppeteer in headless mode. Once that is successful WBOT can run easily.

**Comment by indragunawan82** [comment]
following discussion in here : https://github.com/puppeteer/puppeteer/issues/290   

and tried this suggestion : 
![image](https://user-images.githubusercontent.com/9045625/115965069-94a97680-a551-11eb-8816-3d1b3cd06132.png)

by adding parameter --headless in constants.js
![image](https://user-images.githubusercontent.com/9045625/115965089-ab4fcd80-a551-11eb-826b-2adc1c7d5ffd.png)


it works,
