### ISSUE TITLE
Is possible?

### ISSUE THREAD

**Issue by kivervinicius** [vasani-arpit/WBOT#23]
send a message to a user who does not exist in the contact list.

**Comment by vasani-arpit** [comment]
Yes. It is possible. That user has to be a WhatsApp user though. I really recommend not to do that. As it is considered as spamming.

**Comment by kivervinicius** [comment]
Well I will explain my problem who knows there may be a better way, I would like to send a verification code of mobile via whatsapp (in rural areas there is access to wifi but not mobile network) the mobile that will be installed whatsapp will not have the numbers of my registered clients, however I could export this list periodically and import it into the device, but I see it as a manual job, unless there is some android application that does such synchronization. So I figured it might be possible to send a message to a number that my api knows but the installed device does not.

Sorry, but i used google translate in some parts.

**Comment by vasani-arpit** [comment]
That's a nice analogy I am not sure how Whatsapp will see it. They are very strict when you send message to the person who is not in your contact list. and If you automate that process then you may need to add captcha in your form because in case so many requests comes with random numbers then Whatsapp will ban your account.

**Comment by kivervinicius** [comment]
@vasani-arpit ok, i understand tnks
