### ISSUE TITLE
How to subscribe to the presence of a user?

### ISSUE THREAD

**Issue by amoghh** [vasani-arpit/WBOT#73]
I want to subscribe to the presence of a user. I cannot find a way in which i can use the Store object to trigger a callback when a user comes online or goes offline. Can anyone help me in this, I am new to all of this

**Comment by vasani-arpit** [comment]
Don't worry everybody is now to this so don't worry. we will figure it out together.

First of all there are few things to keep in mind here. First, you must have that number in your contacts otherwise it won't work. Second you need to open that user's chat in phone first to get the callback attached to the process. 

I was able to get it working in using this [repo](https://github.com/alfred82santa/whalesong/blob/master/examples/presencemonitor-chromium.py) a while ago. Now project doesn't build itself in my PC so I am not sure now.

If you able to get it up then let me know. 🙂

**Comment by amoghh** [comment]
Is this still the case? can i not get any presence updates of non contacts or contacts which i havent interacted with? I was just looking into this topic again and i came across multiple apps on playstore who actually do this very accurately for eg.
https://play.google.com/store/apps/details?id=com.wtrack_android
 There must be some way they are using to detect olnline status right? Can anyone throw any light on this? Really intrigued me.
