### ISSUE TITLE
Send messages to groups.

### ISSUE THREAD

**Issue by Dexu5** [vasani-arpit/WBOT#86]
It would be great if I can use the bot to just send my custom messages and not back and forth using any **JSON intent**. The objective is to send the message freely using the methods with a message as the parameter.
Unsure if this can be achievable, just posting it here so it might be considered.

Thanks.

**Comment by vasani-arpit** [comment]
Yes. That is possible in fact you already have the code to achieve that. You just need to rearrange some parts here and there. 

But I'd advise you not to do that because WA considers it as a Bulk-Marketing/Spam activity. so it will ban your phone number immediately. If you still want to try that then you can contact me via email given in readme.md file of the repo.

Thanks & Regards,
